---
title: "Kursinhalte"
description: ""
author: " "
date: " "
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: true
    number_sections: false
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Jede Kurseinheit besteht aus einer Sammlung aus empfohlener Literatur, Vorlesungsfolien und zugehörigen Übungsaufgaben, einschließlich einer kompakten Musterlösung.

## 1. Kursinhalte und Organisatorisches {.tabset .tabset-fade}

In dieser Sitzung besprechen wir die Inhalte der Vorlesung und orientieren uns in der Benutzeroberfläche von R-Studio. Die Installation von R und R-Studio muss vor dem Kurs erfolgt sein. Im Übungsteil machen wir uns mit verschiedenen Datentypen in R und der grundlegenden Syntax mathematischer und logischer Operatoren vertraut.

### Leseempfehlungen

[`r fontawesome::fa("external-link-alt")` What is R?](https://www.r-project.org/about.html)

[`r fontawesome::fa("external-link-alt")` What is R-Studio?](https://en.wikipedia.org/wiki/RStudio)

[`r fontawesome::fa("external-link-alt")` An Introduction to R, Kapitel 1 & 2 (Douglas et al., 2021)](https://intro2r.com/chap1.html)

### Vorlesungsfolien

[`r fontawesome::fa("window-restore")` Folien &raquo;Kursüberblick&laquo; als HTML-Datei öffnen](./slides/01_Vorlesung_Kursueberblick.html) 

[`r fontawesome::fa("file-pdf")` Folien &raquo;Kursüberblick&laquo; als PDF-Datei öffnen](./slides/01_Vorlesung_Kursueberblick.pdf) 

[`r fontawesome::fa("window-restore")` Folien &raquo;Erste Schritte&laquo; als HTML-Datei öffnen](./slides/02_Vorlesung_Erste_Schritte.html) 

[`r fontawesome::fa("file-pdf")` Folien &raquo;Erste Schritte&laquo; als PDF-Datei öffnen](./slides/02_Vorlesung_Erste_Schritte.pdf) 


### Übungsaufgaben

[`r fontawesome::fa("file-pdf")` Übungsblatt &raquo;Hinweise zur Installation von R und RStudio&laquo; als PDF-Datei öffnen](./unterlagen/uebungsaufgaben/00_Uebungsblatt_Hinweise_Installation.pdf) 

[`r fontawesome::fa("file-pdf")` Übungsblatt &raquo;Übungsblatt 1 - Erste Schritte mit R und R-Studio&laquo; als PDF-Datei öffnen](./unterlagen/uebungsaufgaben/01_Uebungsblatt_Erste_Schritte.pdf) 

### Musterlösung

[`r fontawesome::fa("code")` Musterlösung für &raquo;Übungsblatt 1 - Erste Schritte mit R und R-Studio&laquo; als R-Datei öffnen](./unterlagen/musterloesungen/uebung_1.R)

### Daten

`r fontawesome::fa("file-archive")` Keine Daten

## 2. Datenanalyse mit dem Tidyverse {.tabset .tabset-fade}

In dieser Sitzung lernen wir das Tidyverse kennen. Das Tidyverse ist eine Sammlung von R-Paketen, die für die Data Science entwickelt wurden. Alle Pakete teilen eine
zugrunde liegende Design-Philosophie, Grammatik und Datenstrukturen. Wir beschäftigen uns mit der Erweiterbarkeit von Base-R mit Paketen und lernen die moderne Syntax für die Datenanalyse kennen, die wir im Rest des Kurses vertiefen. Darüber hinaus entwickeln wir ein grundsätzliches Verständnis der häufigsten Schritte bei der Datenmanipulation und lernen das Konzept der Tidy Data kennen.

### Leseempfehlungen

[`r fontawesome::fa("external-link-alt")` Tidyverse Cookbook (Grolemund, 2020)](https://rstudio-education.github.io/tidyverse-cookbook/)

### Vorlesungsfolien

[`r fontawesome::fa("window-restore")` Folien &raquo;Einführung in das Tidyverse&laquo; als HTML-Datei öffnen](./slides/03_Vorlesung_Tidyverse.html)


[`r fontawesome::fa("file-pdf")` Folien &raquo;Einführung in das Tidyverse&laquo; als PDF-Datei öffnen](./slides/03_Vorlesung_Tidyverse.pdf)


### Übungsaufgaben

[`r fontawesome::fa("file-pdf")` Übungsblatt &raquo;Übungsblatt 2 - Einführung in das Tidyverse&laquo; als PDF-Datei öffnen](./unterlagen/uebungsaufgaben/02_Uebungsblatt_Intro_Tidyverse.pdf)

### Musterlösung

[`r fontawesome::fa("code")` Musterlösung für &raquo;Übungsblatt 2 - Einführung in das Tidyverse&laquo; als R-Datei öffnen](./unterlagen/musterloesungen/uebung_2.R)

### Daten

[`r fontawesome::fa("file-archive")` Datensatz &raquo;olympics&laquo; als CSV-Datei öffnen](./unterlagen/daten/olympics.csv)

## 3. Umgang mit unordentlichen Daten {.tabset .tabset-fade}

Ein großer Teil der Zeit, die wir &raquo;im echten Leben&laquo; mit der Datenanalyse verwenden, ist für das Säubern von Daten reserviert. Daten werden uns nur selten in einem idealen Format geliefert. Wir lernen in diesem Teil der Veranstaltung einige Konzepte kennen, wie wir aus unordentlichen Daten ordentliche Daten machen können.

### Leseempfehlungen

[`r fontawesome::fa("external-link-alt")` R4DS, Kapitel 12 (Wickham/Grolemund, 2021)](https://r4ds.had.co.nz/tidy-data.html)

[`r fontawesome::fa("external-link-alt")` Data Organization in Spreadsheets (Broman/Woo, 2018)](https://www.tandfonline.com/doi/full/10.1080/00031305.2017.1375989)

[`r fontawesome::fa("external-link-alt")` Tidy Data (Wickham, 2014)](https://www.jstatsoft.org/article/view/v059i10)


### Vorlesungsfolien

[`r fontawesome::fa("window-restore")` Folien &raquo;Säubern von Daten&laquo; als HTML-Datei öffnen](./slides/05_Vorlesung_messy_data_tidy_data.html)

[`r fontawesome::fa("file-pdf")` Folien &raquo;Säubern von Daten&laquo; als PDF-Datei öffnen](./slides/05_Vorlesung_messy_data_tidy_data.pdf)

### Übungsaufgaben

[`r fontawesome::fa("file-pdf")` Übungsblatt &raquo;Übungsblatt 4 - Messy Data &zigrarr; Tidy Data&laquo; als PDF-Datei öffnen](./unterlagen/uebungsaufgaben/04_Uebungsblatt_Messy_Data.pdf)

### Musterlösung

[`r fontawesome::fa("code")` Musterlösung für &raquo;Übungsblatt 4 - Messy Data &zigrarr; Tidy Data&laquo; als R-Datei öffnen](./unterlagen/musterloesungen/uebung_4.R)

### Daten

[`r fontawesome::fa("file-archive")` Datensatz &raquo;Einkommen_Kreise&laquo; als xlsx-Datei öffnen](./unterlagen/daten/Einkommen_Kreise.xlsx)

## 4. Daten verbinden {.tabset .tabset-fade}

Ein Datensatz alleine kann für sich genommen spannende Erkenntnisse bergen. Häufig wird jedoch von uns erwartet, Datensätze aus verschiedenen Quellen zu kombinieren, so neue Forschungsfragen zu generieren und deren Antwort zu finden. In diesem Teil der Veranstaltung lernen wir die verschiedenen Arten kennen, mit denen wir relationale Daten kombinieren können.

### Leseempfehlungen

[`r fontawesome::fa("external-link-alt")` R4DS, Kapitel 13 (Wickham/Grolemund, 2021)](https://r4ds.had.co.nz/relational-data.html)


### Vorlesungsfolien

[`r fontawesome::fa("window-restore")` Folien &raquo;Daten zusammenführen&laquo; als HTML-Datei öffnen](./slides/05_Vorlesung_daten_zusammenfuehren.html)

[`r fontawesome::fa("file-pdf")` Folien &raquo;Daten zusammenführen&laquo; als PDF-Datei öffnen](./slides/05_Vorlesung_daten_zusammenfuehren.pdf)

### Übungsaufgaben

[`r fontawesome::fa("file-pdf")` Übungsblatt &raquo;Übungsblatt 5 - Mutating Joins - Grundlagen&laquo; als PDF-Datei öffnen](./unterlagen/uebungsaufgaben/05_Uebungsblatt_Data_Joins.pdf)

### Musterlösung

[`r fontawesome::fa("code")` Musterlösung für &raquo;Übungsblatt 5 - Mutating Joins - Grundlagen&laquo; als R-Datei öffnen](./unterlagen/musterloesungen/uebung_5.R)

### Daten

[`r fontawesome::fa("file-archive")` Datensatz &raquo;studis_fh_2017&laquo; als CSV-Datei öffnen](./unterlagen/daten/studis_fh_2017.csv)

[`r fontawesome::fa("file-archive")` Datensatz &raquo;studis_fh&laquo; als CSV-Datei öffnen](./unterlagen/daten/studis_fh.csv)

[`r fontawesome::fa("file-archive")` Datensatz &raquo;studis_insg_2017&laquo; als CSV-Datei öffnen](./unterlagen/daten/studis_insg_2017.csv)

[`r fontawesome::fa("file-archive")` Datensatz &raquo;studis_insg&laquo; als CSV-Datei öffnen](./unterlagen/daten/studis_insg.csv)


## 5. Deskriptive Statistiken {.tabset .tabset-fade}

Deskriptive Statistiken bilden einen wichtigen Teil der Datenanalyse. Sie tragen einen entscheidenden Teil zum Gesamtverständnis der analysierten Daten bei, außerdem sind zusammenfassende deskriptive Statistiken zentral für die Wissenschaftskommunikation. Neben der Berechnung zusammenfassender deskriptiver Statistiken lernen wir in diesem Teil des Kurses zudem, wie Häufigkeitsstatistiken für kategoriale Variablen berechnet werden können.

### Leseempfehlungen

<!-- [`r fontawesome::fa("external-link-alt")` R4DS, Kapitel 13 (Wickham/Grolemund, 2021)](https://r4ds.had.co.nz/relational-data.html) -->


### Vorlesungsfolien

[`r fontawesome::fa("window-restore")` Folien &raquo;Deskriptive Statistiken&laquo; als HTML-Datei öffnen](./slides/06_Vorlesung_Deskriptive_Statistiken.html)

[`r fontawesome::fa("file-pdf")` Folien &raquo;Deskriptive Statistiken&laquo; als PDF-Datei öffnen](./slides/06_Vorlesung_Deskriptive_Statistiken.pdf)

### Übungsaufgaben

<!-- [`r fontawesome::fa("file-pdf")` Übungsblatt &raquo;Übungsblatt 5 - Mutating Joins - Grundlagen&laquo; als PDF-Datei öffnen](./unterlagen/uebungsaufgaben/05_Uebungsblatt_Data_Joins.pdf) -->

### Musterlösung

<!-- [`r fontawesome::fa("code")` Musterlösung für &raquo;Übungsblatt 5 -Mutating Joins - Grundlagen&laquo; als R-Datei öffnen](./unterlagen/musterloesungen/uebung_5.R) -->

### Daten

<!-- [`r fontawesome::fa("file-archive")` Datensatz &raquo;studis_fh_2017&laquo; als CSV-Datei öffnen](./unterlagen/daten/studis_fh_2017.csv) -->

<!-- [`r fontawesome::fa("file-archive")` Datensatz &raquo;studis_fh&laquo; als CSV-Datei öffnen](./unterlagen/daten/studis_fh.csv) -->

<!-- [`r fontawesome::fa("file-archive")` Datensatz &raquo;studis_insg_2017&laquo; als CSV-Datei öffnen](./unterlagen/daten/studis_insg_2017.csv) -->

<!-- [`r fontawesome::fa("file-archive")` Datensatz &raquo;studis_insg&laquo; als CSV-Datei öffnen](./unterlagen/daten/studis_insg.csv) -->


## 6. Funktionen & Iteration {.tabset .tabset-fade}

Datenanalyseschritte wiederholen sich häufig. Um Zeit zu sparen und Fehler zu vermeiden, kann es sinnvoll sein, Analyseschritte in Funktionen zu sammeln. In diesem Teil des Kurses werfen wir einen Blick auf den grundsätzlichen Aufbau von Funktionen in R. Wir verbinden diese mit kleinen Besonderheiten, die Tidyverse-Funktionen mit sich bringen, um die bekannte Syntax anwenden zu können. Darüber hinaus wenden wir Funktionen iterativ an.

### Leseempfehlungen

<!-- [`r fontawesome::fa("external-link-alt")` R4DS, Kapitel 13 (Wickham/Grolemund, 2021)](https://r4ds.had.co.nz/relational-data.html) -->


### Vorlesungsfolien

[`r fontawesome::fa("window-restore")` Folien &raquo;Funktionen & Iteration&laquo; als HTML-Datei öffnen](./slides/07_Vorlesung_Funktionen_Iteration.html)

[`r fontawesome::fa("file-pdf")` Folien &raquo;Funktionen & Iteration&laquo; als PDF-Datei öffnen](./slides/07_Vorlesung_Funktionen_Iteration.pdf)

### Übungsaufgaben

<!-- [`r fontawesome::fa("file-pdf")` Übungsblatt &raquo;Übungsblatt 5 - Mutating Joins - Grundlagen&laquo; als PDF-Datei öffnen](./unterlagen/uebungsaufgaben/05_Uebungsblatt_Data_Joins.pdf) -->

### Musterlösung

<!-- [`r fontawesome::fa("code")` Musterlösung für &raquo;Übungsblatt 5 -Mutating Joins - Grundlagen&laquo; als R-Datei öffnen](./unterlagen/musterloesungen/uebung_5.R) -->

### Daten

<!-- [`r fontawesome::fa("file-archive")` Datensatz &raquo;studis_fh_2017&laquo; als CSV-Datei öffnen](./unterlagen/daten/studis_fh_2017.csv) -->

<!-- [`r fontawesome::fa("file-archive")` Datensatz &raquo;studis_fh&laquo; als CSV-Datei öffnen](./unterlagen/daten/studis_fh.csv) -->

<!-- [`r fontawesome::fa("file-archive")` Datensatz &raquo;studis_insg_2017&laquo; als CSV-Datei öffnen](./unterlagen/daten/studis_insg_2017.csv) -->

<!-- [`r fontawesome::fa("file-archive")` Datensatz &raquo;studis_insg&laquo; als CSV-Datei öffnen](./unterlagen/daten/studis_insg.csv) -->
